name: Setup
description: Setup for CI.

inputs:
  llvm-path:
    description: Path to install LLVM to.
    required: true
  llvm-version:
    description: Version of LLVM to install.
    required: true

runs:
  using: composite
  steps:
    - name: Install LLVM Dependencies
      shell: bash
      run: |
        sudo apt update 
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
        sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "${{ inputs.llvm-version }}"
        directory: "${{ inputs.llvm-path }}"

    - name: Install rust
      shell: bash
      run: |
        rustup toolchain install stable --profile minimal --no-self-update

    - uses: Swatinem/rust-cache@v2
